### PR TITLE
Get webhook name from common pkg

### PR DESCRIPTION
**Pull request by arghya88**
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>

Fixes #

## Proposed Changes

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
Great! Thank you!

/lgtm

/cc matzew lberk

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by arghya88** [comment]
@matzew I had to rebase to resolve conflict.PTAL

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
